Repository davidvargas050695/aclFeNIX, pull requests merged in 2024-08, with the labels that each got.

#15 Issue#14
  src/Pages/HomePage/HomePage.css
  src/Pages/HomePage/index.jsx
  src/Pages/Login/Login.css
  src/Pages/UserForm/UserForm.css
  src/Pages/UserForm/index.jsx
Labels: pull-request

#19 Issue#18
  src/App.js
  src/Pages/Client/Client.css
  src/Pages/Client/index.jsx
  src/Pages/ClientForm/ClientForm.css
  src/Pages/ClientForm/index.jsx
  src/Pages/Login/index.jsx
  src/Pages/UserForm/UserForm.css
  src/Pages/UserForm/UserForm.jsx
  src/Pages/UserForm/index.jsx
  src/Pages/index.js
  src/components/Notifications/ErrorNotification/ErrorNotification.css
  src/components/Notifications/ErrorNotification/index.jsx
  src/components/Notifications/InfoNotification/InfoNotification.css
  src/components/Notifications/InfoNotification/index.jsx
  src/components/Notifications/SuccessNotification/SuccessNotification.css
  src/components/Notifications/SuccessNotification/index.jsx
  src/components/Notifications/WarningNotification/WarningNotification.css
  src/components/Notifications/WarningNotification/index.jsx
  src/components/Sidebar/index.jsx
  src/components/index.js
Labels: pull-request

#25 feat: change
  src/App.js
  src/Pages/Admin/Contract.jsx
  src/Pages/Client/index.jsx
  src/Pages/ClientForm/index.jsx
  src/Pages/Customers/index.jsx
  src/Pages/ModulesForm/index.jsx
  src/Pages/index.js
  src/components/Sidebar/index.jsx
Labels: issue

#33 create/edit/delete/search customers, modules, contracts
  .env
  package-lock.json
  package.json
  src/App.js
  src/Pages/Admin/Contract.css
  src/Pages/Admin/Contract.jsx
  src/Pages/Client/Client.css
  src/Pages/Client/index.jsx
  src/Pages/ClientForm/ClientForm.css
  src/Pages/ClientForm/index.jsx
  src/Pages/ContractNew/ContractNew.css
  src/Pages/ContractNew/index.jsx
  src/Pages/Customers/Customer.css
  src/Pages/Customers/index.jsx
  src/Pages/Module/Module.css
  src/Pages/Module/Module.jsx
  src/Pages/ModuleContract/index.jsx
  src/Pages/ModuleNew/ModuleNew.jsx
  src/Pages/ModulesForm/index.jsx
  src/Pages/ModulesList/ModuleList.css
  src/Pages/ModulesList/ModuleList.jsx
  src/Pages/index.js
  src/components/CustomerModal/CustomerModal.css
  src/components/CustomerModal/index.jsx
  src/components/Forms/ContractForm.css
  src/components/Forms/ContractForm.jsx
  src/components/ModulesModal/index.jsx
  src/components/Notifications/ClientProcess/ClientProcess.css
  src/components/Notifications/ClientProcess/index.jsx
  src/components/Notifications/ErrorNotification/ErrorNotification.css
  src/components/Notifications/InfoNotification/InfoNotification.css
  src/components/Notifications/InfoNotification/index.jsx
  src/components/Notifications/SuccessNotification/SuccessNotification.css
  src/components/Notifications/SuccessNotification/index.jsx
  src/components/Notifications/SuccessProcess/SuccessProcess.css
  src/components/Notifications/SuccessProcess/index.jsx
  src/components/Notifications/WarningNotification/WarningNotification.css
  src/components/Notifications/WarningNotification/index.jsx
  src/components/Section/Section.css
  src/components/Sidebar/index.jsx
  src/components/Table/index.jsx
  src/components/Table/table.css
  src/components/index.js
Labels: good first issue, issue
