Repository davidvargas050695/aclFeNIX, pull requests merged in 2024-09, with the labels that each got.

#42 Issue#41
  src/Pages/ContractNew/index.jsx
Labels: issue, pull-request

#51 feat: issue#50
  src/Pages/ModulesForm/index.jsx
Labels: pull-request

#53 feat:close customerModal, load customerModal
  src/components/CustomerModal/index.jsx
Labels: pull-request

#61 feat: change forms
  src/Pages/Admin/Contract.jsx
  src/Pages/ContractEdition/index.jsx
  src/Pages/ContractNew/index.jsx
  src/Pages/ModuleContract/index.jsx
  src/components/Forms/ContractForm.jsx
  src/components/ModulesModal/index.jsx
  src/components/Notifications/ErrorNotification/ErrorNotification.css
  src/components/Notifications/SuccessNotification/SuccessNotification.css
  src/components/Notifications/SuccessNotification/index.jsx
Labels: issue

#65 feat: clear chat
  src/Pages/ClientForm/index.jsx
  src/Pages/ContractNew/index.jsx
  src/Pages/Customers/index.jsx
  src/components/Forms/ContractForm.jsx
  src/components/ModulesModal/index.jsx
Labels: issue

#71 feat: change validations inputs
  src/Pages/ClientForm/index.jsx
  src/components/Forms/ContractForm.jsx
Labels: issue, pull-request
